### ISSUE TITLE
Delete all folders in test/libs to re-enable the user to install them.

### ISSUE THREAD

**Issue by a-t-2** [a-t-2/Setup-Raspberry-Pi-4b-tor-GitLab-website-SSH#10]
Include in readme

chmod +x install-bats-libs.sh
./install-bats-libs.sh

**Comment by a-t-0** [comment]
Most likely this gave an error because the BATS file test library was missing. It is included now and the GitLab CI works with them included. Also, the repository is slightly more robust with the libraries contained instead of as dependency. Hence, this issue is closed for now.
